### ISSUE TITLE
Venv folder name as environment variable?

### ISSUE THREAD

**Issue by 4l1fe** [jeanpantoja/dotpyvenv#3]
Look, i see there is a way to customize a folder name through `.pevenvdir` file, but it leads to manual creation such a file every time  making new folder or in my existent ones. So i usually use `.venv` name.

Why not just to define a name in `.zshrc` config as for example `VENVDIR_NAME` ?

**Comment by jeanpantoja** [comment]
@4l1fe  Something like that can be useful. Probably using other system environment variable name to keep the name convention used by dotpyvenv.

**Comment by 4l1fe** [comment]
As an idea to add a rule on bottom of two:
1. try to find a folder `.pyvenv`
2. try to find a folder name the file `.pyvenvdir` contains
3. try to find a folder with `$CONVETION_VAR_NAME`

**Comment by 4l1fe** [comment]
Well check it out. I've tested it locally.

**Comment by 4l1fe** [comment]
Mention :arrow_up:  once again @jeanpantoja
